name: Create and Release Assets

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Build peoject assets 
        run: |
          npm install
          npm run build
          npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build 
          path: .dist
