name: Build and Release Assets

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v3 
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: true
          #release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
